# Generated by Django 4.1.3 on 2023-05-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
